---
title: ""
format: 
    docx: 
        lang: es
        reference-doc: "extra/doc_templ.docx"
---

```{r}
#| id: Configuración inicial
#| echo: false
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  fig.asp = 1.25
)
```

```{r}
#| id: Cargar paquetes
#| include: false
pacman::p_load(
  flextable,
  scales,
  here,
  rio,
  janitor,
  tidyverse
)


# Tema flextable -----------------------------------------------------------
tab_fmt <- function(x) {
  x |>
    bold(part = "header") |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 9, part = "all") |>
    line_spacing(space = 1.5, part = "all") |>
    valign(valign = "top") |>
    align(align = "left", part = "all") |>
    merge_v(j = 1) |>
    merge_v(j = 2:3, combine = TRUE)
}
```

```{r}
#| id: Cargar datos
datos_gc <- import(here("clean", "arg_defun_recod_2010_2023.rds"))
```

## Tabla 1. Variables incluidas en el estudio y categorías de análisis.

```{r}
#| id: Tabla 1
# Datos para la tabla ----
tab1 <- tibble(
  Variable = c(
    "Año",
    "Región",
    "Jurisdicción",
    "Sexo",
    "Grupo etario",
    "Causa básica de muerte",
    "Grupo de causas",
    "Subgrupo de causas",
    "Número de muertes"
  ),
  Descripción = c(
    "Año de ocurrencia de la defunción",
    "Agrupación territorial definida por la DEIS para resguardar la confidencialidad de los datos",
    "Nivel de agregación jurisdiccional definido por la DEIS para resguardar la confidencialidad de los datos",
    "Sexo consignado en el acta de defunción",
    "Categorías de edad agrupadas según criterios de la DEIS",
    "Causa básica de muerte codificada según la CIE-10",
    "Clasificación de causas según grandes grupos del GBD-2019",
    "Clasificación de causas según grupos nivel 2 del GBD-2019",
    "Cantidad anual de defunciones según región, jurisdicción, sexo, grupo etario y causa básica de muerte"
  ),
  Valores = c(
    "2010-2023",
    paste(levels(datos_gc$region_deis), collapse = "; "),
    paste(levels(datos_gc$jurisdiccion), collapse = "; "),
    "Masculino; Femenino",
    paste(levels(datos_gc$grupo_edad), collapse = "; "),
    "A00.0-Z99.9",
    "CMNN; ENT; CE; GC",
    "CMNN; DM; ECV; ERC; NPL; OENT; TRA; SU; HO; OCE; GC1; GC2; GC3; GC4; NNE",
    "0-Inf"
  )
)

# Formato tabla -----
tab1 |>
  flextable() |>
  tab_fmt() |>
  width(width = c(3, 7, 7), unit = "cm")
```

\newpage
## Tabla 2. Principales códigos *garbage* de nivel 1 y 2 (GC1-GC2) registrados como causa básica de defunción en Argentina (2010-2023).

```{r}
#| id: Tabla 2
## Datos para la tabla -----
tab2 <- datos_gc |>
  # Filtrar GC1-GC2
  filter(paso1 %in% c("GC1", "GC2")) |>

  # Reagrupar niveles
  mutate(
    cie10_cod = if_else(
      cie10_cod == "A41.9",
      cie10_cod,
      str_sub(cie10_cod, 1, 3)
    )
  ) |>

  # Frecuencia muertes
  count(Código = cie10_cod, wt = n) |>
  mutate(pct = percent(n / sum(n), accuracy = .1, decimal.mark = ",")) |>

  # Filtrar por frecuencia
  arrange(-n) |>
  filter_out(n < 20000) |>

  # Añadir descripción
  mutate(
    Causa = c(
      "Insuficiencia cardíaca",
      "Otras causas mal definidas y no especificadas de mortalidad",
      "Insuficiencia respiratoria",
      "Septicemia no especificada",
      "Neumonitis por alimentos o vómito",
      "Insuficiencia renal no especificada",
      "Otras enfermedades del sistema digestivo",
      "Hipertensión esencial (primaria)",
      "Exposición a factor no especificado",
      "Shock, no clasificado en otra parte",
      "Edema pulmonar",
      "Insuficiencia renal aguda",
      "Otras muertes súbitas de causa desconocida",
      "Embolia pulmonar",
      "Peritonitis"
    ),
    .after = "Código"
  )


# Formato tabla -----
tab2 |>
  flextable() |>
  tab_fmt() |>
  width(width = c(2, 8, 3, 3), unit = "cm")
```